language: java
jdk:
- openjdk7
sudo: required
cache: ccache
before_install:
- export PATH="/usr/lib/ccache:${PATH}"
install:
- sudo apt-get install -qyy lzop git-core gnupg flex bison gperf build-essential zip zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip maven schedtool
before_script:
- git config --global user.email "you@example.com"
- git config --global user.name "Your Name"
- git config --global color.ui true
- mkdir ~/bin
- curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
- chmod a+x ~/bin/repo
- export PATH=~/bin:$PATH
- mkdir ~/twrp
- cd ~/twrp
- repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-6.0
- repo sync -j2

# we need toolchain for compiling kernel
- cd $HOME
- git clone https://github.com/aapav01/aarch64-linux-android-4.9-linaro --depth=1
- export CROSS_COMPILE=$PWD/aarch64-linux-android-4.9-linaro/bin/aarch64-linux-android-
- export ARCH=arm64
- export PATH=$PATH:$PWD/aarch64-linux-android-4.9-linaro/bin/
- aarch64-linux-android-gcc --version

script:
- cd ~/twrp
- git clone https://github.com/akuhak/xcover3ltexx_custom_kernel kernel/samsung/xcover3lte --depth=1
- git clone https://github.com/akuhak/android_device_samsung_xcover3lte --depth=1 --branch test --single-branch device/samsung/xcover3lte
- rm -rf bootable/recovery
- git clone https://github.com/omnirom/android_bootable_recovery bootable/recovery
- source ./build/envsetup.sh
- lunch omni_xcover3lte-eng
#- make -j4 bootimage
- mka -j2 recoveryimage
# - mkazip_delos3geur
# - cd out/target/product/delos3geur/
# - tar -H ustar -c "recovery.img" > "recovery.tar"

# deploy:
  # skip_cleanup: true
  # provider: releases
  # api_key:
    # secure: Fj/7CtoYzYY9OEzQu9R52dU6BFIWf0DKZ2J6MYIMILnzyQfkuP/wU5LdlBDom9CDeGqDdgaOndVuqHCats+wpYHV6IzsgoKH+3vlLHn2eDEXasbim8Li4IurXwdVEi0ZILJu8CGZxTSglg7xAyVMcepnL8Q/C1SaTvfeJi+Yt6t84G883zk6G2GMamaTh/yZM2atInDqIBNRNHH3JhX6/gfQqyiZjsG94Gy80j2YrnW4UQcH9jsAUykk3Ma29EFsh9Lk/+YJFhYr1Y0knvzWDnCkj7lepc8UgPu9D0BJx+20rC9SWDIcFDuy7oaJeAnKf39U6RcVSeESvmjN4UWMLLrO16D9eS0eDDeCV9BSjm8zo64+YsaWOtj6NjPd84G+4iUqETefz/1+9ofzUiDBwLGI90XZNW8W1rSSbRG+fh30mfZ3PKEUHIkqt6gTDOtmhU8XrIrThLLeB30x6j6MmiybQYvR13b8Zz1LbS1DXWQkY14DXdHIaJnX8tKkJ1BKQb4jjatW3tdq64BL9K+APUlWlU9GA3iYOSvv7z19vDV46E3DGbsQ7+MzD3wCklxJB/FVkP26a5q39yiENPFak6sBkRGZDzidaKUX8Fj1Y0i0mXmWNLW1c5F/agRoCYNH7Ly2xSD9stWqK5cuWzwUC9ALkrKBpUGScdmg0Qhzw0Y=
  # file:
    # - recovery.tar
    # - recovery.img
    # - twrp-$(date +%Y%m%d)-3.1.0-UNOFFICIAL-delos3geur.zip
  # on:
    # repo: I8552-CM/twrp_device_delos3geur
    # branch: mm6.0
